name: Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config

      - name: Deploy Elasticsearch
        run: kubectl apply -f deploy/k8s/elasticsearch.yaml

      - name: Deploy Kibana
        run: kubectl apply -f deploy/k8s/kibana.yaml
