name: Deploy to K3s (Search Namespace)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > ~/.kube/config
          kubectl config use-context default-context

      - name: Deploy RBAC and Applications
        run: |
          # Apply RBAC for search namespace
          cat <<EOF | kubectl apply -f -
          apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: github-actions-role
            namespace: search
          rules:
          - apiGroups: ["", "apps", "networking.k8s.io", "batch", "extensions"]
            resources: ["*"]
            verbs: ["*"]
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: github-actions-binding
            namespace: search
          subjects:
          - kind: ServiceAccount
            name: github-actions
            namespace: github-actions
          roleRef:
            kind: Role
            name: github-actions-role
            apiGroup: rbac.authorization.k8s.io
          EOF
          
          # Deploy applications
          kubectl apply -n search -f deploy/k8s/elasticsearch.yaml
          kubectl apply -n search -f deploy/k8s/kibana.yaml

      - name: Verify deployments
        run: |
          echo "Deployment status:"
          kubectl get pods -n search || echo "Could not verify deployment status. Continuing..."
